### ISSUE TITLE
Shadowlands 9.0 Data Import

### ISSUE THREAD

**Issue by seirl** [kevinclement/SimpleArmory#306]
- [x] Achievements (done in b3ed5a293b047c825a2a227b0aca993c69b8512c)
- [x] Mounts (done in 4e1e77215c769c0d898ee2c564cb47b9a3034)
- [x] Battle Pets (done in #318 )
- [x] Companions (done in #320 )
- [x] Toys (done in db79182300c99e471090db7b0f478addc8185710)
- [x] Factions (done in #310 )

**Comment by lgkern** [comment]
Hey, thanks for updating the site for Shadowlands. For mounts, I see it checked as complete but it is still missing Kyrian mounts (Phalynxes for instance https://www.wowhead.com/shadowlands-mount-guide#kyrian-mounts)

**Comment by seirl** [comment]
Thanks, I'll check with the API.

**Comment by slemke** [comment]
I noticed this too when doing the import from the API (2 weeks ago). They might be available now. Shadowlands was/is still pretty much in development. The wowhead guide also had wrong data at that point because I looked up every mount coming from the API.

**Comment by slemke** [comment]
I just checked, they now show up via the API. I'll add a pull request with the new data.

**Comment by slemke** [comment]
I added a PR for shadowlands factions #310. I tried with the pets, but that would be a complete overhaul of the current script, because the pets list from the api does only contain name and id. You need to send a separate request for each pet to get data like sources or abilities. Maybe I can take a look in a week or so.
